# Generated by Django 3.1.1 on 2020-09-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_provider',
            options={},
        ),
    ]
